### ISSUE TITLE
Specs of the RPi5?

### ISSUE THREAD

**Issue by pknetworksolutions** [valtsu23/DIY-Emu-Black-Dash-Rpi5#1]
What RAM spec is needed at minimum?

**Comment by valtsu23** [comment]
All Rpi5 versions have plenty of memory for this application. I think memory usage is less than 512Mb. 
I'll check how much memory is in use, when I can and report here.

**Comment by valtsu23** [comment]
![screenshot_20240911_025410](https://github.com/user-attachments/assets/0b383d3f-923a-4ce3-a56a-12b9592ee16d)
Memory usage is less than 200Mb
